import {
  WebSocketGateway,
  WebSocketServer,
  SubscribeMessage,
  MessageBody,
  ConnectedSocket,
  OnGatewayConnection,
  OnGatewayDisconnect,
} from '@nestjs/websockets';
import { Server, Socket } from 'socket.io';
import { KDSService, KDSTicketStatus } from './kds.service';

@WebSocketGateway({
  cors: {
    origin: '*',
  },
  namespace: '/kds',
})
export class KDSGateway implements OnGatewayConnection, OnGatewayDisconnect {
  @WebSocketServer()
  server!: Server;

  constructor(private readonly kdsService: KDSService) {}

  async handleConnection(client: Socket) {
    console.log(`[KDS WebSockets] Client connected: ${client.id}`);
    // Emit initial tickets
    const tickets = await this.kdsService.getAllTickets();
    client.emit('kds:initial_tickets', tickets);
  }

  handleDisconnect(client: Socket) {
    console.log(`[KDS WebSockets] Client disconnected: ${client.id}`);
  }

  @SubscribeMessage('kds:join_hub')
  handleJoinHub(@ConnectedSocket() client: Socket, @MessageBody() hubId: string) {
    client.join(`hub_${hubId}`);
    console.log(`[KDS WebSockets] Client ${client.id} joined kitchen hub: hub_${hubId}`);
    return { event: 'kds:hub_joined', data: { hubId, status: 'CONNECTED' } };
  }

  @SubscribeMessage('kds:update_status')
  async handleUpdateStatus(
    @ConnectedSocket() client: Socket,
    @MessageBody() payload: { ticketId: string; nextStatus: KDSTicketStatus; chefId?: string }
  ) {
    try {
      const updatedTicket = await this.kdsService.updateTicketStatus(payload.ticketId, payload.nextStatus);

      // Broadcast update to all kitchen tablet screens and admin monitors
      this.server.emit('kds:ticket_updated', updatedTicket);

      console.log(
        `[KDS WebSockets] Ticket ${payload.ticketId} updated to ${payload.nextStatus} by chef ${payload.chefId || 'station'}`
      );

      return { status: 'SUCCESS', ticket: updatedTicket };
    } catch (err: any) {
      return { status: 'ERROR', message: err.message };
    }
  }

  /**
   * Helper to broadcast new tickets generated by the 05:00 WIB BullMQ worker
   */
  public broadcastNewTickets(tickets: any[]) {
    if (this.server) {
      this.server.emit('kds:batch_tickets_dispatched', tickets);
    }
  }
}
